rm -rf build
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/.local -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=DEBUG -DUSE_FORTRAN=OFF -DUSE_PYTHON=ON
#cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/.local -DCMAKE_C_COMPILER=xlc -DCMAKE_CXX_COMPILER=xlC -DCMAKE_BUILD_TYPE=DEBUG -DUSE_FORTRAN=OFF -DUSE_PYTHON=ON
make -j install

#export CPATH=$CPATH:$HOME/.local/include
#export LIBRARY_PATH=$LIBRARY_PATH:$HOME/.local/lib64

