rm -rf build
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/.local -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=DEBUG -DUSE_CUDA=OFF -DUSE_HIP=ON -DUSE_OPENCL=ON -DUSE_OPENMP=OFF
make -j install

