BRISBANE 	:= $(HOME)/.local/
CC				:= g++
#CC				:= xlC
C_FLAGS		:= -I$(BRISBANE)/include -g
LD_INC		:= -L$(BRISBANE)/lib64
LD_FLAGS	:= -lbrisbane -lpthread -ldl

$(TEST):$(TEST).c
	$(CC) $(C_FLAGS) -o $@ $^ $(LD_INC) $(LD_FLAGS)

clean:
	rm -f $(TEST)

