BRISBANE 	:= ../../
CC			:= g++
LD_INC		:= -L$(BRISBANE)/install/lib
LD_FLAGS	:= -lbrisbane -lOpenCL -lpthread -ldl
C_FLAGS		:= -I$(BRISBANE)/install/include -g

$(TEST):$(TEST).c
	$(CC) $(C_FLAGS) -o $@ $^ $(LD_INC) $(LD_FLAGS)

clean:
	rm -f $(TEST)

