PROGRAM SAXPY
    USE BRISBANE
    IMPLICIT NONE

    INTEGER :: I, IERROR
    INTEGER(KIND=8) :: SIZE

    REAL(4),DIMENSION(:),ALLOCATABLE :: A
    REAL(4),DIMENSION(:),ALLOCATABLE :: B
    REAL(4),DIMENSION(:),ALLOCATABLE :: C

    TYPE(BRISBANE_MEM), POINTER :: MEM_A
    TYPE(BRISBANE_MEM), POINTER :: MEM_B
    TYPE(BRISBANE_MEM), POINTER :: MEM_C

    TYPE(BRISBANE_TASK), TARGET :: TASK
    TYPE(BRISBANE_TASK), POINTER :: TASK_P

    CALL BRISBANE_INIT(IERROR)
    IF (IERROR /= BRISBANE_OK) THEN
        PRINT*, 'FAILED AT INIT'
    ENDIF

    SIZE = 10

    ALLOCATE(A(SIZE))
    ALLOCATE(B(SIZE))
    ALLOCATE(C(SIZE))

    DO I = 1, SIZE
        A(I) = I
        B(I) = I * 100
        C(I) = 0
    ENDDO

    CALL BRISBANE_MEM_CREATE(4 * SIZE, MEM_C, IERROR)
    IF (IERROR /= BRISBANE_OK) THEN
        PRINT*, 'FAILED AT MEM_CREATE'
    ENDIF

    TASK_P => TASK

    CALL BRISBANE_TASK_CREATE(TASK_P, IERROR)
    IF (IERROR /= BRISBANE_OK) THEN
        PRINT*, 'FAILED AT TASK_CREATE'
    ENDIF

    CALL BRISBANE_TASK_SUBMIT(TASK_P, BRISBANE_CPU, .TRUE., IERROR)
    IF (IERROR /= BRISBANE_OK) THEN
        PRINT*, 'FAILED AT TASK_CREATE'
    ENDIF

    DO I = 1, SIZE
        PRINT*, 'C[', I, '] ', C(I)
    ENDDO

    DEALLOCATE(A)
    DEALLOCATE(B)
    DEALLOCATE(C)

    CALL BRISBANE_FINALIZE(IERROR)
    IF (IERROR /= BRISBANE_OK) THEN
        PRINT*, 'FAILED AT FINALIZE'
    ENDIF

END PROGRAM SAXPY
